package com.ilyabuglakov.task06book.bean;

public enum MessageName {
    WRONG_INT_INPUT,
    TRY_AGAIN,
    ENTER_BOOK,
    ENTER_BOOK_NAME,
    ENTER_NUMBER_OF_PAGES,
    ENTER_AUTHORS,
    ENTER_PUBLISHING_HOUSE,
    ENTER_YEAR_OF_PUBLISHING,
    ENTER_STRING,
    FILE_IS_EMPTY,
    CANT_OPEN_FILE,
    CANT_CREATE_FILE,
    CHOOSE_LOCALE,
    NOTHING_TO_READ
}
