package src.com.ilyabuglakov.arraymanipulator.controller;

public enum CommandName {
    EXIT,
    FILL_ARRAY,
    INPUT_ARRAY,
    SHOW_ARRAY,
    RANDOM_ARRAY,
    //File array
    INDEX_OF,
    INDEX_OF_ARRAY,
    INDEX_OF_JUGGED_ARRAY,
    FIND_MAX,
    FIND_MIN,
    SWITCH_TYPE,
    SWITCH_TO_ARRAY,
    SWITCH_TO_JUGGED_ARRAY,
    SORT_ARRAY,
    SORT_ARRAY_SHELL,
    SORT_ARRAY_MERGE,
    SORT_ARRAY_INSERTION,
    BINARY_SEARCH,
    FIND_SIMPLE_NUMBERS,
    FIND_FIB_NUMBERS,
    FIND_THREE_DIGITS_UNIQUE,
    FILL_JUGGED_ARRAY,
    INPUT_JUGGED_ARRAY,
    RANDOM_JUGGED_ARRAY,
    //File juggedArray
}
