package com.ilyabuglakov.task0201books.bean;

/**
 * Defines the name of the message
 */
public enum MessageName {
    WRONG_INT_INPUT,
    TRY_AGAIN,
    ENTER_BOOK,
    ENTER_BOOK_NAME,
    ENTER_NUMBER_OF_PAGES,
    ENTER_AUTHORS,
    ENTER_PUBLISHING_HOUSE,
    ENTER_YEAR_OF_PUBLISHING,
    FILE_INIT_ERROR,
    WRONG_INPUT_FILE_FORMAT,
    INPUT_FILE_FORMAT,
    BOOK_ALREADY_EXIST,
    BOOK_DUPLICATES_IN_FILE,
    BOOK_IS_MISSING,
    CANT_OPEN_FILE,
    CHOOSE_SORT_TYPE
}
